library("tidyr")
library(ggplot2)
links = read.csv("/Users/BindiPatel/Desktop/ml-latest-small 3/links.csv", header = TRUE)
tags = read.csv("/Users/BindiPatel/Desktop/ml-latest-small 3/tags.csv", header = TRUE)
ratings = read.csv("/Users/BindiPatel/Desktop/ml-latest-small 3/ratings.csv", header = TRUE)
movies = read.csv("/Users/BindiPatel/Desktop/ml-latest-small 3/movies.csv", header = TRUE)
df=merge(movies,ratings, by="movieId")
df=merge(df,tags,by="movieId")
df = subset(df, select = -c(timestamp.y,userId.y,timestamp.x) )
df=separate(data = df, col = genres, into = c("G1", "G2", "G3", "G4", "G5"), sep = "\\|")